# Site settings
title: "Hanguang's Demo Site"
email: "186768789+hanguang9527@users.noreply.github.com"
email2: ""
description: > # this means to ignore newlines until "baseurl:"
  My Personal Website
  
baseurl: "/drum" # the subpath of your site, e.g. /blog/
url: "https://hanguang9527.github.io" # the base hostname & protocol for your site

# Social media
twitter_username: ""
github_username: "hanguang9527"
cv_username: ""
phone: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages specific
repository: hanguang9527/drum
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENCE

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/